easy_admin:
    entities:
        # List the entity class name you want to manage
#        - App\Entity\Product
#        - App\Entity\Category
        - App\Entity\User
        - App\Entity\Jouer
        - App\Entity\Partie
        - App\Entity\Cases
        - App\Entity\Carte
        - App\Entity\Acquisitions
        - App\Entity\Tchats
